'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Volvox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Advanced_scripting_with_Volvox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Advanced_scripting_with_Volvox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Basic_Operations() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Basic_Operations", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Clipping_planes() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Clipping_planes", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Crc32C_NET() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Crc32C_NET", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;doc&gt;
        '''    &lt;assembly&gt;
        '''        &lt;name&gt;Crc32C.NET&lt;/name&gt;
        '''    &lt;/assembly&gt;
        '''    &lt;members&gt;
        '''        &lt;member name=&quot;T:Crc32C.Crc32CAlgorithm&quot;&gt;
        '''            &lt;summary&gt;
        '''            Implementation of CRC-32C (Castagnoli) with polynomial 0x1EDC6F41.
        '''            It can detect errors more reliably than the older CRC-32-IEEE.
        '''            This class will use CRC32 instruction on recent Intel processors if it is available.
        '''            Otherwise it will transparently fall back to a very fast softw [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Crc32C_NET1() As String
            Get
                Return ResourceManager.GetString("Crc32C_NET1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property E57LibCommon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("E57LibCommon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property E57LibReader() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("E57LibReader", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property E57LibWriter() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("E57LibWriter", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property EngineX_vs_Engine() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EngineX_vs_Engine", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Expression_Dictionary() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Expression_Dictionary", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please read the following licences.
        '''Volvox is shipped with a CRC-32C library by Robert Važan, and you can find the licence description below.
        '''
        '''______________________________________
        '''
        '''Volvox Licence
        '''The MIT License (MIT)
        '''Copyright (c) 2016 DURAARK
        '''
        '''Permission is hereby granted, free of charge, to any person obtaining a copy
        '''of this software and associated documentation files (the &quot;Software&quot;), to deal
        '''in the Software without restriction, including without limitation the rights
        '''to use, copy, modify [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Licence() As String
            Get
                Return ResourceManager.GetString("Licence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Load_E57() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Load_E57", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property LoadAndSave() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("LoadAndSave", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Scanner_Position() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Scanner_Position", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Selection() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Selection", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UnVolvox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UnVolvox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property UserData() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("UserData", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Volvox() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Volvox", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Volvox_Cloud() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Volvox_Cloud", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Volvox_Instr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Volvox_Instr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Volvox_Python() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Volvox_Python", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property VolvoxIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("VolvoxIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
